import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { AllSpaceBox } from "@/components/AllSpaceBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen overflow-hidden flex flex-col`}
      >
        <Header />
        <AllSpaceBox className="!overflow-hidden">{children}</AllSpaceBox>
      </body>
    </html>
  );
}
